amcl:
  ros__parameters:
    use_sim_time: true
    odom_frame_id: odom
    base_frame_id: base_link
    scan_topic: /laser/out
    robot_model_type: "differential"
    update_min_d: 0.2
    update_min_a: 0.2

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "../maps/maze2_map.yaml"

planner_server:
  ros__parameters:
    use_sim_time: true

controller_server:
  ros__parameters:
    use_sim_time: true

bt_navigator:
  ros__parameters:
    use_sim_time: true

recovery_server:
  ros__parameters:
    use_sim_time: true

