controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_vel_x: 0.0
    max_vel_x: 0.26
    min_vel_y: 0.0
    max_vel_y: 0.0
    min_vel_theta: -1.82
    max_vel_theta: 1.82
    dwb_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      # List of critics to use
      critics: ["GoalAlignCritic", "PathAlignCritic", "OscillationCritic", "ObstacleFootprintCritic", "RotateToGoal"]
