slam_toolbox:
  ros__parameters:
    mode: mapping  
    odom_frame: "odom"
    base_frame: "base_link"
    map_frame: "map"
    scan_topic: "/scan"
    map_update_interval: 0.05
    max_laser_range: 3.0
    use_scan_matching: true
    use_loop_closure: false
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0
    use_sim_time: true
    use_pose_graph: false
